training:
  # Basic training parameters
  batch_size: 64
  final_epoch: 20
  learning_rate: 0.001
  random_seed: 2665
  scheduler: 'CosineAnnealingLR'

  # GPU configuration
  use_cuda: true
  gpu_setting: "0" # A string that is passed as an environment variable

  # Path for saving model and performance data
  save_path: "/tmp2/pfe/fscl/cb_at_m_cf/b064_t0d03_ep050"

model: # pre-trained model that we want to train its classifier head
  num_attributes: 1  # Number of attributes for BinaryModel
  model_path: "/tmp2/pfe/fscl/cb_at_m_supcon_b064_t0d03/checkpoint_epoch_0050.pth"

# Provides dataset information to correctly load the appropriate dataloader
dataset:
  task_name: 'Attractive'    # This string is displayed while printing the performance to the console.
  training_schema: 'fscl classifier' # Defines how the dataset is loaded
  name: 'celeba' # Name of the dataset
  type: 'binary' # 'binary' or 'multi-class'; determines which fairness metrics are available
  balanced: false
  selected_attrs:
    - Attractive
  protected_attr: 'Male'
  num_outputs: 1