training:
  # Basic training parameters
  batch_size: 256
  final_epoch: 150
  learning_rate: 0.001
  random_seed: 2665
  scheduler: 'CosineAnnealingLR'

  # GPU configuration
  use_cuda: true
  gpu_setting: "0" # A string that is passed as an environment variable

  # Optional: Path for loading pre-trained model weights
  # load_path:
  # load_stats:
  # Path for saving model and performance data
  save_path: "/tmp2/pfe/fscl/supcon/cb_at_m_b256_t0d005"

fscl:
  temperature: 0.005

# Provides dataset information to correctly load the appropriate dataloader
dataset:
  task_name: 'Attractive'    # This string is displayed while printing the performance to the console.
  training_schema: 'fscl supcon' # Defines how the dataset is loaded
  name: 'celeba' # Name of the dataset
  type: 'binary' # 'binary' or 'multi-class'; determines which fairness metrics are available
  balanced: true
  selected_attrs:
    - Attractive
  protected_attr: 'Male'
  num_outputs: 1