plotting: 
  stats_file_path: /tmp2/pfe/model/cb_at_m_b64/stats_end_0030.pt
  metrics:
    - accuracy
    - equalized_odds
  epoch:
    start: 1
    end: 30
  save_path: './analysis/cb_at_m_b64'

  type: 'binary' # 'binary' or 'multi-class'
  task_name: 'Attractive'
