training:
  batch_size: 128
  # num_epochs: 10
  random_seed: 2665

  use_cuda: true
  gpu_id: 1

  save_path: "./"

model:
  num_attributes: 2  # Number of attributes for BinaryModel
  model_path: "/tmp2/npe/model/celeba_test/checkpoint_epoch_0002.pth"

attack:
  # support pattern perturbation, frame, eyeglasses
  pattern_type: perturbation
  alpha: 0.001          # Step size per attack iteration
  iters: 1             # Number of attack iterations
  base_path: /tmp2/npe/pert/celeba_test/pattern_epoch_0002.pt

  epsilon: 0.063        # used if parttern is perturbation
  frame_thickness: 0.05 # used if parttern is frame

dataset:
  name: 'celeba'
  type: 'binary' # 'binary' or 'multi-class'
  selected_attrs:
    - Smiling
    - Young
  protected_attr: 'Male'