plotting: 
  stats_file_path: /tmp2/pfe/model/celeba_attractive_male/stats_end_0030.pt
  type: 'binary' # 'binary' or 'multi-class'
  metrics:
    - accuracy
    - equalized_odds
  epoch:
    start: 1
    end: 30
  first_epoch_num: 1 # 0 only for pattern trainer
  attributes: # use for the title in the diagram, no checking is involved
    - Attractive
  save_path: './analysis/celeba_mdl'