plotting: 
  stats_file_path: /tmp2/pfe/model/cb_at_m_b128/stats_end_0020.pt
  metrics:
    - accuracy
    - equalized_odds
  epoch:
    start: 1
    end: 20
  save_path: './analysis/cb_at_m_b128'

  type: 'binary' # 'binary' or 'multi-class'
  task_name: 'Attractive'
