model:
  num_attributes: 2  # Number of attributes for BinaryModel
  model_path: "/tmp2/npe/model/celeba_test/checkpoint_epoch_1.pth"

training:
  batch_size: 128
  num_epochs: 10
  random_seed: 2665

  use_cuda: true
  gpu_id: 3

  save_path: "/tmp2/npe/pert/celeba_test"

attack:
  epsilon: 0.03  # Maximum perturbation size
  alpha: 0.01   # Step size per attack iteration
  iters: 1     # Number of attack iterations
  base_path: null

dataset:
  name: 'celeba'
  selected_attrs:
    - Smiling
    - Young
    
  protected_attr: 'Male'