training:
  method: generic
  # Basic training parameters
  batch_size: 128
  final_epoch: 30
  learning_rate: 0.001
  random_seed: 2665
  scheduler: null

  # GPU configuration
  use_cuda: true
  gpu_id: 0

  # Optional: Path for loading pre-trained model weights
  # load_path:
  # load_stats:
  # Path for saving model and performance data
  save_path: "/tmp2/pfe/model/celeba_highcheekbones_male"

dataset:
  name: 'celeba'
  type: 'binary' # 'binary' or 'multi-class'
  selected_attrs:
    - High_Cheekbones
  protected_attr: 'Male'