training:
  method: generic
  # Basic training parameters
  batch_size: 64
  final_epoch: 4
  learning_rate: 0.001
  random_seed: 2665
  scheduler: null

  # GPU configuration
  use_cuda: true
  gpu_id: 1

  # Optional: Path for loading pre-trained model weights
  load_path: "/tmp2/npe/model/celeba_test/checkpoint_epoch_0002.pth"
  load_stats: "/tmp2/npe/model/celeba_test/stats_end_0002.pt"
  # Path for saving model and performance data
  save_path: "/tmp2/npe/model/celeba_test"

dataset:
  name: 'celeba'
  type: 'binary' # 'binary' or 'multi-class'
  selected_attrs:
    - Smiling
    - Young
  protected_attr: 'Male'