training:
  # Basic training parameters
  batch_size: 64
  num_epochs: 2
  learning_rate: 0.001
  random_seed: 2665

  # GPU configuration
  use_cuda: true
  gpu_id: 5

  # Path for saving model and performance data
  save_path: "/tmp2/npe/model/ham10000_test"

dataset:
  name: 'ham10000'
  class_number: 7
  
  selected_attr: 'diagnosis'
  protected_attr: 'sex'